apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: circleguard-alertmanager
  namespace: monitoring
  labels:
    alertmanagerConfig: circleguard
spec:
  route:
    groupBy: ['alertname', 'namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    receiver: slack-receiver
  receivers:
    - name: slack-receiver
      slackConfigs:
        - apiURL:
            name: alertmanager-slack
            key: webhook-url
          channel: '#circleguard-alerts'
          title: '{{ .GroupLabels.alertname }}'
          text: >-
            {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }}
              *Severity:* {{ .Labels.severity }}
              *Namespace:* {{ .Labels.namespace }}
            {{ end }}
          sendResolved: true
