apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: circleguard-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
        version: v1
    spec:
      containers:
        - name: file-service
          image: magusa17/circleguard-file:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: circleguard-dev
spec:
  selector:
    app: file-service
  ports:
    - port: 8085
      targetPort: 8085
