apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: circleguard-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: circleguard/identity-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/circleguard
            - name: SPRING_DATASOURCE_USERNAME
              value: circleguard
            - name: SPRING_DATASOURCE_PASSWORD
              value: circleguard
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: circleguard-master
spec:
  selector:
    app: identity-service
  ports:
    - port: 8080
      targetPort: 8080
