apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: circleguard-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
        version: v1
    spec:
      containers:
        - name: gateway-service
          image: magusa17/circleguard-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: stage
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          readinessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: circleguard-stage
spec:
  selector:
    app: gateway-service
  ports:
    - port: 8087
      targetPort: 8087
