---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: circleguard-db-credentials
  namespace: circleguard-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: circleguard-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: cg-db-password-stage
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: circleguard-jwt-secret
  namespace: circleguard-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: circleguard-jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: cg-jwt-secret-stage
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: circleguard-mail-credentials
  namespace: circleguard-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: circleguard-mail-credentials
    creationPolicy: Owner
  data:
    - secretKey: mail-password
      remoteRef:
        key: cg-mail-password-stage
