apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: circleguard-stage
spec:
  provider:
    gcpsm:
      projectID: circleguard-final
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: circleguard-stage
          serviceAccountRef:
            name: eso-sa
            namespace: external-secrets
